language: node_js
node_js:
  - 7

cache:
  cache: npm

before_install:
  - npm install --save nuxt

install:
  - npm install

before_script:
  - export TZ=Asia/Taipei

script:
  - npm run generate:gh-pages
  - npm run build:gh-pages
  - npm run deploy

branches:
  only:
    - master
